title: "Forecasting San Diego Power Consumption"
author: '"Saba_Alemayehu"'
date: "2022-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(rstudioapi)
library(parsedate)
library(lubridate)
library(tidyverse)
```
```{r}
### San Diego Energy Data
SD <- read.csv("~/University of San Diego/ADS_506_Applied_Time_Serious/Module two/Project/SD.csv")
```

```{r}
#Display rows and columns
dim(SD)
```

```{r}
#View the first six row
#head(SD)
```

```{r}
#Select Hourly Variables
SD <- SD %>% select(Date, SDGE, starts_with("Hourly"))
```

```{r}
str(SD)
```
```{r}
#basic summary statistics about the data
summary(SD)
```
```{r}
# sum of missing values per column
colSums(is.na(SD))
```
```{r}
# Checking the class
class(SD)
```
# Preprocessing
```{r}
### Convert character Date to date-time class

SD$Date <- as_datetime(SD$Date)
```
```{r}
#visualizing missing values
missing.values <- SD %>%
    gather(key = "key", value = "val") %>%
    mutate(is.missing = is.na(val)) %>%
    group_by(key, is.missing) %>%
    summarise(num.missing = n()) %>%
    filter(is.missing==T) %>%
    select(-is.missing) %>%
    arrange(desc(num.missing)) 
missing.values %>%
  ggplot() +
    geom_bar(aes(x=key, y=num.missing), stat = 'identity') +
    labs(x='variable', y="number of missing values", title='Number of missing values') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# Preprocessing
### Convert character Date to date-time class

SD$Date <- as_datetime(SD$Date)

#convert "HourlyDryBulbTemperature"to numeric because we will focus only on the ‘HourlyDryBulbTemperature’ which is the outside temperature in deg F.
SD$HourlyDryBulbTemperature <- as.numeric(as.character(SD$HourlyDryBulbTemperature))

#Missing Value Imputation by Last Observation Carried Forward(na_locf)
#Perform LOCF and remove remaining NAs
SD$HourlyDryBulbTemperature<-na.locf(SD$HourlyDryBulbTemperature, na_remaining = "rm")

# Extraction of time components
#extract date
SD$date<-as.Date(SD$Date,format = "%y-%m-%d")

#Extract Year 
SD$year<-format(SD$Date,"%Y")

#extract the month
SD$month<-format(SD$Date,"%m")

#extract the hour
SD$hour<-format(SD$Date, format = "%H")

#Numeric Day of Week (Assuming Week Starts on Monday)
#In this scenario, a 1 indicates a Monday, 2 indicates a Tuesday, and so on
SD$weakday<-wday(SD$Date, week_start=1)



#Visualising the Time Series
#In this project we will analyze past 4 years of hourly energy consumption data of SDGE utility to find trends in energy consumption around hour of the day, day of the week, season of the year, etc., and also to check if factors like outside temperature and solar installations in the region affect the energy consumption.

SDGE.ts<-ts(SD$SDGE, start = c(2019,1), frequency = 24*365.25)

# view the plot
autoplot(SDGE.ts) +
theme_classic()
```
